services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
## If want database to be running on docker container than uncomment below      
    # depends_on:
    #   - db
    restart: always
    volumes:
      - ./backend:/app
      - ./backend/uploads:/usr/src/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    restart: always
    volumes:
      - ./frontend:/app
## If want database to be running on docker container than uncomment below
#   db:
#     image: postgres:16
#     env_file:
#       - ./backend/.env
#     ports:
#       - "5432:5432"
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#     restart: always
# volumes:
#   pgdata:

volumes:
  uploads_data:
