FROM jenkins/agent:latest-jdk17 as jenkinagent
FROM python:3.12.8-bullseye

LABEL maintainer="robokingmaster@gmail.com"

ARG HELM_VERSION=v3.17.1
ARG TERRAFORM_VERSION=1.10.5
ARG CLOUD_SDK_VERSION=507.0.0
ARG AWS_AUTHENTICATOR_VERSION=0.6.29
ARG SSH_USER=''
ARG SSH_PWD=''

ENV JAVA_HOME=/opt/java/openjdk \
    JAVA_VERSION=$OPENJDK_VERSION \
    JENKINS_HOME=/home/jenkins \
    JENKINS_AGENT=/usr/share/jenkins \
    CLOUD_SDK_VERSION=$CLOUD_SDK_VERSION \
    PATH=/google-cloud-sdk/bin:/usr/local/bin:/opt/java/openjdk/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH 

COPY --from=jenkinagent /usr/share/jenkins/agent.jar /usr/share/jenkins/agent.jar
COPY --from=jenkinagent /opt/java/openjdk /opt/java/openjdk
COPY --from=jenkinagent /usr/share/jenkins /usr/share/jenkins

# Install Basic Packages
RUN apt-get -y update && \
	apt-get -y upgrade && \
    apt-get -y install \
        ca-certificates \
        tzdata \
        bash \
        curl \ 
        expect \
        git \
        gnupg \
        jq \
        make \
        openssl \ 
        openssh-server \
        openssh-client \
        openrc \
        sudo \
        libpq-dev \
        gcc \
        g++ \
        musl-dev \
        gnupg \
        sshpass \
        libaio1 \
        libnsl2 \
        vim

RUN mkdir /var/run/sshd && \
    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# Creating Python Virtual Environment
RUN python3 -m venv python3-env && \
    . python3-env/bin/activate 

# Install kubectl
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
    && sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl \
    && chmod +x kubectl \
    && mkdir -p ~/.local/bin \
    && mv ./kubectl ~/.local/bin/kubectl

# Install helm
RUN curl https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz -o helm.tar.gz \
	&& tar -xvf helm.tar.gz \
	&& rm helm.tar.gz \
	&& mv linux-amd64/helm /usr/local/bin/helm \
	&& chmod +x /usr/local/bin/helm \
	&& helm version

# Install Terraform
RUN curl https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip -o terraform.zip \
    && unzip terraform.zip \
    && rm terraform.zip \
    && mv terraform /usr/local/bin/ \
    && terraform --version 
    
# Install Pip Modules
RUN	python3 -m pip install --upgrade --no-cache-dir pip && \
    python3 -m pip install --upgrade --ignore-installed --no-cache-dir git+https://github.com/vmware/vsphere-automation-sdk-python.git@v8.0.3.0
    
# Install Pip Modules ASW CLI/Google Cloud
RUN python3 -m pip install --upgrade --force-reinstall --no-cache-dir \ 
        virtualenv==20.28.0 \ 
        jinja2==3.1.4 \ 
        psycopg2-binary==2.9.8 \ 
        psycopg2==2.9.10 \
        pyodbc==5.2.0 \           
        hvac==2.3.0 \
        cryptography==41.0.5 \
        netaddr==1.3.0 \
        scp==0.15.0 \
        jmespath==1.0.1 \
        pbr==5.11.1 \
        ruamel.yaml==0.18.6 \
        kubernetes==31.0.0 \        
        cassandra-driver==3.29.2 \
        lz4==4.3.3 \
        python-snappy==0.7.3 \
        confluent-kafka==2.6.1 \
        lxml==5.3.0 \
        awscli \
        setuptools \
        boto3 \
        requests \
        numpy \
        pandas

# Install Ansdible ansible-core==2.15.0 becuase kubespray 2.23  support only till ansible 2.15.0
RUN python3 -m pip install --upgrade --no-cache-dir \ 
        ansible==11.1.0 \
        ansible-core==2.18.1

# Add Jenkins User
RUN adduser --system jenkins --home ${JENKINS_HOME} && \
    chown -R jenkins ${JENKINS_HOME} && \
    chmod 755 ${JENKINS_AGENT}   

# Install Google Cloud SDK
RUN if [ `uname -m` = 'x86_64' ]; then echo -n "x86_64" > /tmp/arch; else echo -n "arm" > /tmp/arch; fi;
RUN ARCH=`cat /tmp/arch` && \
    curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-${CLOUD_SDK_VERSION}-linux-${ARCH}.tar.gz && \
    tar xzf google-cloud-cli-${CLOUD_SDK_VERSION}-linux-${ARCH}.tar.gz && \
    rm google-cloud-cli-${CLOUD_SDK_VERSION}-linux-${ARCH}.tar.gz && \
    chmod +x /google-cloud-sdk/bin/gcloud && \
    gcloud config set core/disable_usage_reporting true && \
    gcloud config set component_manager/disable_update_check true && \
    gcloud config set metrics/environment github_docker_image && \
    gcloud components install gke-gcloud-auth-plugin --quiet && \
    gcloud components install beta --quiet && \
    gcloud --version && \
    gke-gcloud-auth-plugin --version
RUN git config --system credential.'https://source.developers.google.com'.helper gcloud.sh
VOLUME ["/root/.config"]  

# Install aws-iam-authenticato
RUN curl -Lo aws-iam-authenticator https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/download/v${AWS_AUTHENTICATOR_VERSION}/aws-iam-authenticator_${AWS_AUTHENTICATOR_VERSION}_linux_amd64 \
    && chmod +x ./aws-iam-authenticator \
    && mv ./aws-iam-authenticator /usr/local/bin/ \    
    && aws-iam-authenticator version       

# Install aws eksctl
RUN ARCH=amd64 && \
    PLATFORM=$(uname -s)_$ARCH && \
    curl -sLO "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$PLATFORM.tar.gz" && \
    tar -xzf eksctl_$PLATFORM.tar.gz -C /tmp && rm eksctl_$PLATFORM.tar.gz && \
    sudo mv /tmp/eksctl /usr/local/bin

# Script To Start SSH Serivice As Container Starts
COPY entrypoint.v6.0.sh /entrypoint.sh

# Creating Labops User Account
RUN chmod 777 /entrypoint.sh \
    && adduser --system --shell /bin/bash --home /home/${SSH_USER} ${SSH_USER} \
    && echo "${SSH_USER} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers \
    && echo "${SSH_USER}:${SSH_PWD}" | sudo chpasswd \
    && echo ". /python3-env/bin/activate" >> /root/.profile
    
# Printing Installed Versions
RUN python3 --version && \
    pip --version && \
    java --version && \
    aws --version && \
    eksctl version && \
    env

WORKDIR ${JENKINS_HOME}
# USER jenkins
USER root

ENTRYPOINT ["/entrypoint.sh"]

# docker build --tag eis-devops-agent:v6.0 --build-arg SSH_USER=<ansibleuser> --build-arg SSH_PWD=<ansiblepwd> .
# docker run -it eis-devops-agent:v6.0 /bin/bash
