FROM jenkins
LABEL maintainer="robokingmaster@gmail.com"
USER root
RUN apt-get update && apt-get install -y docker.io && rm -rf /var/lib/apt/lists/*
USER jenkins

# docker build --tag custom-jenkins:latest .
# docker run -it custom-jenkins:latest /bin/bash