name: Validate Push

on:
  push:
    paths:
      - 'projects-demo/**'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_projects: ${{ steps.set.outputs.changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch base branch
        run: git fetch origin ${{ github.base_ref }}

      - name: Get changed project folders
        id: set
        run: |
          CHANGED=$(git diff --name-only origin/${{ github.base_ref }} |
            grep '^projects-demo/' |
            awk -F'/' '{print $1"/"$2"/"$3}' |
            sort -u)
          
          if [ -z "$CHANGED" ]; then
            echo "changed=[]" >> $GITHUB_OUTPUT
          else
            JSON=$(echo "$CHANGED" | jq -R . | jq -s . | tr -d '\n')
            echo "changed=$JSON" >> $GITHUB_OUTPUT
          fi

  build-and-test:
    needs: detect-changes
    if: needs.detect-changes.outputs.changed_projects != '[]'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ${{ fromJson(needs.detect-changes.outputs.changed_projects) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image for ${{ matrix.project }}
        run: |
          docker build -t devopsstudio-temp:${{ matrix.project }} ./${{ matrix.project }}

      - name: Run tests for ${{ matrix.project }}
        run: |
          docker run --rm devopsstudio-temp:${{ matrix.project }} npm test
