name: Validate Push

on:
  push:
    paths:
      - 'projects-demo/**'

env:
  APP_ENV: devlopment
  APP_LOG_LEVEL: debug  

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_projects: ${{ steps.set.outputs.changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed project folders
        id: set
        run: |
          CHANGED=$(git diff --name-only HEAD^ HEAD |
            grep '^projects-demo/' |
            awk -F'/' '{print $3}' |
            sort -u)

          if [ -z "$CHANGED" ]; then
            echo "changed=[]" >> $GITHUB_OUTPUT
          else
            JSON=$(echo "$CHANGED" | jq -R . | jq -s . | tr -d '\n')
            echo "changed=$JSON" >> $GITHUB_OUTPUT
          fi

  build-and-test:
    needs: detect-changes
    if: needs.detect-changes.outputs.changed_projects != '[]'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ${{ fromJson(needs.detect-changes.outputs.changed_projects) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Locate project folder
        id: locate
        run: |
          PROJECT_PATH=$(find projects-demo -type d -name "${{ matrix.project }}" | head -n 1)
          echo "path=$PROJECT_PATH" >> $GITHUB_OUTPUT

      - name: Build Docker image for ${{ matrix.project }}
        run: |
          docker build -t ${{ matrix.project }}:temp ${{ steps.locate.outputs.path }}

      ## Perfoming Test Before Pushing Image
      - name: Create Docker Network
        run: docker network create docker-network

      - name: Start PostgreSQL Container
        env:
          POSTGRESS_DBNAME: ${{ secrets.POSTGRESS_DBNAME }}
          POSTGRESS_DBUSER: ${{ secrets.POSTGRESS_DBUSER }}
          POSTGRESS_DBPASSWORD: ${{ secrets.POSTGRESS_DBPASSWORD }}
        run: |
          docker run -d --name test-pgdb --network docker-network \
            -e POSTGRES_USER=$POSTGRESS_DBUSER \
            -e POSTGRES_PASSWORD=$POSTGRESS_DBPASSWORD \
            -e POSTGRES_DB=$POSTGRESS_DBNAME \
            -p 5432:5432 \
            postgres:16

      - name: Wait for Postgres
        env:
          POSTGRESS_DBNAME: ${{ secrets.POSTGRESS_DBNAME }}
          POSTGRESS_DBUSER: ${{ secrets.POSTGRESS_DBUSER }}
          POSTGRESS_DBPASSWORD: ${{ secrets.POSTGRESS_DBPASSWORD }}      
        run: |
          for i in {1..30}; do
            if docker exec test-pgdb pg_isready -U $POSTGRESS_DBUSER; then
              echo "Postgres is ready"
              break
            fi
            echo "Waiting for Postgres..."
            sleep 2
          done

      - name: Load test database with inventory schema
        env:
          POSTGRESS_DBNAME: ${{ secrets.POSTGRESS_DBNAME }}
          POSTGRESS_DBUSER: ${{ secrets.POSTGRESS_DBUSER }}
          POSTGRESS_DBPASSWORD: ${{ secrets.POSTGRESS_DBPASSWORD }}
        run: |
          cd ${{ steps.locate.outputs.path }}
          if [ -f "resources/database-schema/database-schema.sql" ]; then
            echo "Creating Database Schema . . ."
            docker cp ./resources/database-schema/database-schema.sql test-pgdb:/tmp/schema.sql
            docker exec test-pgdb psql -U $POSTGRESS_DBUSER -d $POSTGRESS_DBNAME -f /tmp/schema.sql
          fi       

      - name: Run tests suites for ${{ matrix.project }}
        env:
          POSTGRESS_DBNAME: ${{ secrets.POSTGRESS_DBNAME }}
          POSTGRESS_DBUSER: ${{ secrets.POSTGRESS_DBUSER }}
          POSTGRESS_DBPASSWORD: ${{ secrets.POSTGRESS_DBPASSWORD }}
          APP_JWT_SECRET: ${{ secrets.APP_JWT_SECRET }}
          APP_DEFAULT_USER: ${{ secrets.APP_DEFAULT_USER }}
          APP_DEFAULT_PWD: ${{ secrets.APP_DEFAULT_PWD }}    
        run: |
          cd ${{ steps.locate.outputs.path }}
          if [ -f "package.json" ]; then
            docker run --rm --name app-testsuite --network docker-network \
              -e DATABASE_HOST=test-pgdb \
              -e DATABASE_PORT=5432 \
              -e POSTGRES_USER=$POSTGRESS_DBUSER \
              -e POSTGRES_PASSWORD=$POSTGRESS_DBPASSWORD \
              -e POSTGRES_DBNAME=$POSTGRESS_DBNAME \
              -e APP_ENV=$APP_ENV \
              -e APP_PORT=5000 \
              -e APP_LOG_LEVEL=$APP_LOG_LEVEL \
              -e APP_DEFAULT_USER=$APP_DEFAULT_USER \
              -e APP_DEFAULT_PWD=$APP_DEFAULT_PWD \
              -e APP_JWT_SECRET=$APP_JWT_SECRET \
              -p 5000:5000 \
              ${{ matrix.project }}:temp \
              npm test           
          elif [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
            pytest
          else
            echo "No recognizable test setup found."
          fi

      - name: Run container and test startup
        env:
          POSTGRESS_DBNAME: ${{ secrets.POSTGRESS_DBNAME }}
          POSTGRESS_DBUSER: ${{ secrets.POSTGRESS_DBUSER }}
          POSTGRESS_DBPASSWORD: ${{ secrets.POSTGRESS_DBPASSWORD }}
          APP_JWT_SECRET: ${{ secrets.APP_JWT_SECRET }}
          APP_DEFAULT_USER: ${{ secrets.APP_DEFAULT_USER }}
          APP_DEFAULT_PWD: ${{ secrets.APP_DEFAULT_PWD }}    
        run: |
          cd ${{ steps.locate.outputs.path }}
          if [ -f "package.json" ]; then
            docker run --rm --name ${{ matrix.project }} --network docker-network \
              -e DATABASE_HOST=test-pgdb \
              -e DATABASE_PORT=5432 \
              -e POSTGRES_USER=$POSTGRESS_DBUSER \
              -e POSTGRES_PASSWORD=$POSTGRESS_DBPASSWORD \
              -e POSTGRES_DBNAME=$POSTGRESS_DBNAME \
              -e APP_ENV=$APP_ENV \
              -e APP_PORT=5000 \
              -e APP_LOG_LEVEL=$APP_LOG_LEVEL \
              -e APP_DEFAULT_USER=$APP_DEFAULT_USER \
              -e APP_DEFAULT_PWD=$APP_DEFAULT_PWD \
              -e APP_JWT_SECRET=$APP_JWT_SECRET \
              -p 5000:5000 \
              ${{ matrix.project }}:temp \

            echo "Waiting for container to start..."
            sleep 15

            if [ -f "views/login.html" ]; then
              echo "Checking if ${{ matrix.project }} app web login page is running..."

              if ! curl --silent --output /dev/null --write-out "%{http_code}" http://localhost:5000/login | grep -q "^200$"; then
                echo "App failed to start application"
                docker logs ${{ matrix.project }}
                exit 1
              else
                echo "✅ Application ${{ matrix.project }} is up and responding to login page"
              fi  
            fi            
          elif [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
            pytest
          else
            echo "No recognizable test setup found."
          fi

