name: PR Check - NodeJS Projects

on:
  pull_request:
    paths:
      - 'nodejs/**'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_projects: ${{ steps.filter.outputs.changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get changed folders
        id: filter
        run: |
          CHANGED=$(git diff --name-only origin/main | grep '^nodejs/' | cut -d'/' -f2 | sort -u)
          echo "Changed folders: $CHANGED"
          echo "changed=$(echo $CHANGED | jq -R -s -c 'split("\n") | map(select(length > 0))')" >> $GITHUB_OUTPUT

  build-and-test:
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ${{ fromJson(needs.detect-changes.outputs.changed_projects) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image for ${{ matrix.project }}
        run: |
          docker build -t devopsstudio-temp:${{ matrix.project }} ./nodejs/${{ matrix.project }}

      - name: Run tests for ${{ matrix.project }}
        run: |
          docker run --rm devopsstudio-temp:${{ matrix.project }} npm test
